name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    environment:
      name: github-pages
      url: https://energizer91.github.io/telia-test/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist